"""ICICI Direct API Service Wrapper.

Handles connection caching, thread-safe session validation,
and historical options data retrieval.
"""
from __future__ import annotations

import asyncio
import logging
import threading
from datetime import datetime
from typing import Any, Dict, List, Optional

from breeze_connect import BreezeConnect

from ..config import get_settings

logger = logging.getLogger("signal_ai")


class MockBreezeConnect:
    def __init__(self, api_key: str):
        self.api_key = api_key

    def generate_session(self, api_secret: str, session_token: str):
        pass

    def get_historical_data(
        self,
        interval: str,
        from_date: str,
        to_date: str,
        stock_code: str,
        exchange_code: str,
        product_type: str,
        expiry_date: str,
        right: str,
        strike_price: str,
    ) -> dict[str, Any]:
        logger.info("MockBreezeConnect: generating mock historical option data")
        return {
            "Success": [
                {
                    "datetime": "2026-06-01 09:15:00",
                    "open": 150.5,
                    "high": 165.2,
                    "low": 148.0,
                    "close": 158.4,
                    "volume": 5200,
                    "open_interest": 125000,
                },
                {
                    "datetime": "2026-06-02 09:15:00",
                    "open": 158.4,
                    "high": 172.0,
                    "low": 155.1,
                    "close": 169.8,
                    "volume": 6800,
                    "open_interest": 132000,
                },
                {
                    "datetime": "2026-06-03 09:15:00",
                    "open": 169.8,
                    "high": 180.5,
                    "low": 167.3,
                    "close": 175.2,
                    "volume": 4900,
                    "open_interest": 139000,
                },
            ]
        }


class ICICIDirectClient:
    # Class-level cache to keep the authenticated connection alive.
    # The session_token generated by ICICI Direct is valid for 24 hours.
    _breeze_instance: Optional[BreezeConnect | MockBreezeConnect] = None
    _active_session_token: Optional[str] = None
    _lock = threading.Lock()

    def __init__(self):
        self.settings = get_settings()

    def _get_connection(self) -> BreezeConnect | MockBreezeConnect:
        """Retrieve or initialize a cached/authenticated BreezeConnect instance."""
        from .redis_client import get_breeze_credentials

        creds = get_breeze_credentials()
        api_key = creds.get("app_key") or self.settings.icici_client_id or "mock_app_key"
        secret_key = creds.get("secret_key") or self.settings.icici_secret_key or "mock_secret_key"
        session_id = creds.get("session_id") or "mock_session"

        with self._lock:
            # Re-use the existing instance if the session token hasn't changed
            if (
                ICICIDirectClient._breeze_instance is not None
                and ICICIDirectClient._active_session_token == session_id
            ):
                return ICICIDirectClient._breeze_instance

            if session_id.startswith("mock") or "paste" in session_id:
                logger.info("Initializing MockBreezeConnect client session...")
                breeze = MockBreezeConnect(api_key=api_key)
                ICICIDirectClient._breeze_instance = breeze
                ICICIDirectClient._active_session_token = session_id
                return breeze

            # Initialize a new BreezeConnect client
            logger.info("Initializing new BreezeConnect client session using Redis credentials...")
            breeze = BreezeConnect(api_key=api_key)
            try:
                # generate_session authenticates the client via ICICI Servers.
                # Note: this makes a synchronous HTTP network request under the hood.
                breeze.generate_session(
                    api_secret=secret_key,
                    session_token=session_id,
                )
                logger.info("Successfully authenticated Breeze session.")
            except Exception as e:
                logger.error("Failed to generate Breeze session: %s", e)
                raise ValueError(f"Breeze session generation failed: {e}") from e

            ICICIDirectClient._breeze_instance = breeze
            ICICIDirectClient._active_session_token = session_id
            return breeze

    @staticmethod
    def _normalize_date(date_str: str, time_suffix: str = "T00:00:00.000Z") -> str:
        """Convert standard dates (YYYY-MM-DD) to ISO-8601 required by Breeze.

        Expected output: YYYY-MM-DDTHH:MM:SS.000Z
        """
        date_str = date_str.strip()
        if "T" in date_str:
            return date_str
        # If it's a simple YYYY-MM-DD
        if len(date_str) == 10:
            return f"{date_str}{time_suffix}"
        
        # If it has spaces
        try:
            dt = datetime.strptime(date_str, "%Y-%m-%d %H:%M:%S")
            return dt.strftime("%Y-%m-%dT%H:%M:%S.000Z")
        except ValueError:
            pass

        try:
            dt = datetime.strptime(date_str, "%Y-%m-%d %H:%M")
            return dt.strftime("%Y-%m-%dT%H:%M:00.000Z")
        except ValueError:
            pass

        return date_str

    @staticmethod
    def _normalize_right(right_str: str) -> str:
        """Map PE/CE option type tags to put/call expected by Breeze API."""
        r = right_str.upper().strip()
        if r in ("PE", "PUT"):
            return "put"
        if r in ("CE", "CALL"):
            return "call"
        raise ValueError(f"Invalid option right identifier '{right_str}'. Must be CE, PE, call, or put.")

    @staticmethod
    def _normalize_interval(interval_str: str) -> str:
        """Map internal timeframe strings to supported Breeze intervals.

        Breeze supports: 1second, 1minute, 5minute, 30minute, 1day
        """
        i = interval_str.lower().strip()
        if i in ("1m", "1min", "1minute"):
            return "1minute"
        if i in ("5m", "5min", "5minute"):
            return "5minute"
        if i in ("30m", "30min", "30minute"):
            return "30minute"
        if i in ("1d", "1day", "day"):
            return "1day"
        if i in ("1s", "1sec", "1second"):
            return "1second"
        
        # Fallback/default if unknown
        logger.warning("Unknown interval '%s'. Defaulting to 1minute.", interval_str)
        return "1minute"

    @staticmethod
    def _normalize_datetime_response(dt_str: str) -> str:
        """Format the datetime field in response to a standard YYYY-MM-DD HH:MM:SS naive IST string."""
        if not dt_str:
            return ""
        # Handle formats like "2025-02-03T09:20:00.000Z" or "2025-02-03 09:20:00"
        clean = dt_str.replace("T", " ")
        if "." in clean:
            clean = clean.split(".")[0]
        if "Z" in clean:
            clean = clean.replace("Z", "")
        return clean.strip()

    def fetch_historical_options_sync(
        self,
        stock_code: str,
        expiry_date: str,
        right: str,
        strike_price: float,
        from_date: str,
        to_date: str,
        interval: str = "1minute",
    ) -> List[Dict[str, Any]]:
        """Synchronously calls Breeze SDK to fetch historical options data."""
        breeze = self._get_connection()

        # Format inputs
        norm_expiry = self._normalize_date(expiry_date, time_suffix="T07:00:00.000Z")
        norm_from = self._normalize_date(from_date, time_suffix="T00:00:00.000Z")
        norm_to = self._normalize_date(to_date, time_suffix="T23:59:59.000Z")
        norm_right = self._normalize_right(right)
        norm_interval = self._normalize_interval(interval)

        logger.info(
            "Fetching Breeze F&O historical data: symbol=%s strike=%s right=%s expiry=%s from=%s to=%s interval=%s",
            stock_code, strike_price, norm_right, norm_expiry, norm_from, norm_to, norm_interval
        )

        # Call get_historical_data
        try:
            resp = breeze.get_historical_data(
                interval=norm_interval,
                from_date=norm_from,
                to_date=norm_to,
                stock_code=stock_code.upper().strip(),
                exchange_code="NFO",
                product_type="options",
                expiry_date=norm_expiry,
                right=norm_right,
                strike_price=str(int(strike_price)),  # Breeze API wants integer or string strike
            )
        except Exception as e:
            logger.error("Breeze SDK error: %s", e)
            raise RuntimeError(f"Breeze SDK error: {e}") from e

        if not resp:
            raise RuntimeError("Breeze API returned an empty or null response.")

        # Check for errors in the response dict
        error_msg = resp.get("Error")
        if error_msg:
            # Note: Breeze sometimes returns 'Success' as None or empty if there's an Error
            raise RuntimeError(f"Breeze API Error: {error_msg}")

        raw_candles = resp.get("Success") or []
        
        # If Success is returned but is a string describing an empty response
        if isinstance(raw_candles, str):
            logger.warning("Breeze API returned text instead of list for Success: %s", raw_candles)
            return []

        formatted_candles = []
        for candle in raw_candles:
            # Map fields safely:
            # Breeze returns keys like: datetime, open, high, low, close, volume, open_interest / oi
            dt = self._normalize_datetime_response(candle.get("datetime") or candle.get("date") or "")
            if not dt:
                continue

            # Fetch open interest if available
            oi_val = candle.get("open_interest") or candle.get("oi") or 0

            formatted_candles.append({
                "time": dt,
                "open": float(candle.get("open") or 0.0),
                "high": float(candle.get("high") or 0.0),
                "low": float(candle.get("low") or 0.0),
                "close": float(candle.get("close") or 0.0),
                "volume": int(candle.get("volume") or 0),
                "oi": int(oi_val),
            })

        return formatted_candles

    async def fetch_historical_options(
        self,
        stock_code: str,
        expiry_date: str,
        right: str,
        strike_price: float,
        from_date: str,
        to_date: str,
        interval: str = "1minute",
    ) -> List[Dict[str, Any]]:
        """Asynchronously calls Breeze SDK in a threadpool to avoid blocking FastAPI."""
        return await asyncio.to_thread(
            self.fetch_historical_options_sync,
            stock_code=stock_code,
            expiry_date=expiry_date,
            right=right,
            strike_price=strike_price,
            from_date=from_date,
            to_date=to_date,
            interval=interval,
        )
